plugins {
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dependency.management)
    alias(libs.plugins.jooq.codegen)
    id 'java'
}

group = 'dev.hambacon'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-jooq'
    implementation 'org.springframework.boot:spring-boot-starter-flyway'
    implementation libs.jooq
    implementation libs.springdoc.openapi
    implementation libs.flyway.core
    implementation libs.flyway.postgresql
    runtimeOnly 'org.postgresql:postgresql'
    jooqCodegen libs.jooq.meta
    jooqCodegen libs.jooq.meta.extensions

    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-restclient-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-jooq-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
}

tasks.named('test') {
    useJUnitPlatform()
}

jooq {
    configuration {
        generator {
            database {
                name = 'org.jooq.meta.extensions.ddl.DDLDatabase'
                properties {
                    property {
                        key = 'scripts'
                        value = 'src/main/resources/db/migration/V1__create_bank_schema.sql'
                    }
                    property {
                        key = 'sort'
                        value = 'semantic'
                    }
                    property {
                        key = 'defaultNameCase'
                        value = 'lower'
                    }
                }
            }
            target {
                packageName = 'dev.hambacon.bank.adapter.out.persistence.jooq'
                directory = 'build/generated-src/jooq/main'
            }
        }
    }
}

sourceSets {
    main {
        java {
            srcDir 'build/generated-src/jooq/main'
        }
    }
}

tasks.named('compileJava') {
    dependsOn tasks.named('jooqCodegen')
}
